version: '3.9'

services:
  frontend:
    container_name: portfolio-front
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/var/www/frontapp'
      - '/var/www/frontapp/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true