name: Deploy to Cpanel
on:
  push:
    branches:
      - master
jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
        REACT_APP_URL: ${{secrets.REACT_APP_UR}}
        REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
        file_name: .env
        fail_on_empty: false
        sort_keys: false
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
          server: ${{ secrets.PORTFOLIO_FTP_SERVER }}
          username: ${{ secrets.PORTFOLIO_FTP_NAME }}
          password: ${{ secrets.PORTFOLIO_FTP_PASSWORD }}
          port: ${{ secrets.PORTFOLIO_FTP_PORT }}
          local-dir: build/