name: Deploy to Cpanel
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install

    - name: Create .env files
      run: |
        echo GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP > .env
        echo APP_API_URL=$APP_API_URL >> .env
        echo APP_URL=$APP_URL >> .env
      env:
        GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_URL: ${{ secrets.REACT_APP_URL }}

    - name: 🔨 Build Project
      run: npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
          server: ${{ secrets.PORTFOLIO_FTP_SERVER }}
          username: ${{ secrets.PORTFOLIO_FTP_NAME }}
          password: ${{ secrets.PORTFOLIO_FTP_PASSWORD }}
          port: ${{ secrets.PORTFOLIO_FTP_PORT }}
          local-dir: build/